from django.urls import path
from . import views


urlpatterns = [ 
    path('genshiptoken',views.genshiptoken),
    path('',views.userlogin,name='userlogin'),
    path('otpverify/<mobile>',views.otpverify,name='otpverify'),
    path('adminlogin',views.adminlogin,name='adminlogin'),
    path('register',views.register,name='register'),
    path('userlogout',views.userlogout,name='userlogout'),
    path('myaccount',views.myaccount,name='myaccount'),
    path('updateprofile',views.updateprofile,name='updateprofile'),
    path('orderdetails',views.orderdet,name='orderdet'),
    path('download',views.download,name='download'),
    path('address',views.address,name='address'),
    path('addaddress',views.addaddress,name='addaddress'),
    path('addbilladdress',views.addbilladdress,name='addbilladdress'),
    path('editaddress/<uid>',views.editaddress,name='editaddress'),
    path('editbilladdress/<uid>',views.editbilladdress,name='editbilladdress'),
    path('account-info',views.account_info,name="account_info"),
    path('checkout',views.checkout,name='checkout'),
    path('paymentresponse',views.paymentresponse,name='paymentresponse'),
    path('paymentcallback',views.paymentcallback,name='paymentcallback'),

    path('dashboard',views.dashboard,name='dashboard'),

    path('addcategory',views.addcategory,name='addcategory'),
    path('delcategory/<uid>',views.delcategory,name='delcategory'),
    path('addsubcategory',views.addsubcategory,name='addsubcategory'),
    path('delsubcategory/<uid>',views.delsubcategory,name='delsubcategory'),
    path('addbrands',views.addbrands,name='addbrands'),
    path('delbrands/<uid>',views.delbrands,name='delbrands'),

    path('addproduct',views.addproduct,name='addproduct'),
    path('editproduct/<uid>',views.editproduct,name='editproduct'),
    path('addproductimage/<uid>',views.addproductimage,name='addproductimage'),
    path('delproduct/<uid>',views.delproduct,name='delproduct'),
    path('delproductimage/<uid>',views.delproductimage,name='delproductimage'),
    path('allproduct',views.allproduct,name='allproduct'),
    path('managepage',views.managepage,name='managepage'),
    path('delmanagepage',views.delmanagepage,name='delmanagepage'),
    path('searchproduct',views.searchproduct,name='searchproduct'),
    path('userdetails',views.userdetails,name='userdetails'),

    path('pending',views.pending,name='pending'),
    path('packed',views.packed,name='packed'),
    path('pending',views.pending,name='pending'),
    path('ontheway',views.on_the_way,name='on_the_way'),
    path('delivered',views.delivered,name='delivered'),
    path('canceled',views.cancel,name='cancel'),
    path('change-status',views.change_status,name='change_status'),
    path('contactform',views.contactform,name='contactform'),
    path('delcontact/<uid>',views.delcontact,name='delcontact'),
    path('bills/<uid>',views.bills,name='bills'),


    # path('checkoutaddress',views.checkoutaddress,name='checkoutaddress'),
    # path('checkout-add',views.checkout_add,name='checkout-add'),
    # path('myaccountdel/<int:pid>',views.myaccountdel,name='myaccountdel'),
    # path('subscribe',views.subscribe,name='subscribe'),

    # path('checkout',views.checkout,name='checkout'),
    # path('placedorder',views.placedorder,name='placedorder'),
    # path('paynow',views.paynow,name='paynow'),
    # path('payment',views.payment,name='payment'),
    # path('paymentresponse',views.paymentresponse,name='paymentresponse'),
    # path('paymentcallback',views.paymentcallback,name='paymentcallback'),
    # path('order',views.order,name='order'),
    # path('invoice/<int:cid>',views.invoice,name='invoice'),
    # path('orderview/<int:cid>',views.orderview,name='orderview'),
    # path('remove-coupon/<pid>',views.remove_coupon,name="remove_coupon"),
    # path('shipcreate',views.shipcreate),
]