# Generated by Django 4.2.7 on 2024-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_orderplaced_color_varient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
