# Generated by Django 4.2.7 on 2023-12-13 07:57

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('overview', ckeditor.fields.RichTextField()),
                ('time_upload', models.DateField(blank=True)),
                ('author', models.CharField(max_length=25)),
                ('slug', models.CharField(blank=True, default='', max_length=130, unique=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('publish', models.BooleanField()),
            ],
            options={
                'ordering': ['-time_upload'],
            },
        ),
    ]
